### ISSUE TITLE
android Scrolling issue?

### ISSUE THREAD

**Issue by RyuWoong** [actbase/react-daum-postcode#4]
안드로이드 스크롤이 부드럽게 되지 않고 버벅이는? 터치이벤트를 여러번 해야되는거 같은데 어떤가요?

**Comment by ChanghyeonYoon** [comment]
@RyuWoong 해당 기능을 구현한 소스코드 첨부 부탁드립니다.

**Comment by RyuWoong** [comment]
이래저래 뜯어고치면서 코드를 날렸는데, 모달안에 postcode를 사용하는 방식으로 했었습니다.
스크롤 했을때 뭔가 두번 눌려야하는? 문제가 있었는데 새프로젝트하면서 하니까 또 보이질 않네요. 원인이 뭐였는지는.. 우선 닫도록 하겠습니다.
